- name: Install Jenkins
  hosts: all
  remote_user: ec2-user

  tasks:
    - name: update dnf repo
      command: sudo dnf update

    - name: Install PIP
      dnf:
        name: python3-pip
        state: latest
      become: true

    - name: Install Java17
      dnf:
        name: java-17-amazon-corretto.x86_64
        state: latest
      become: true

    - name: Update Repo with Jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      become: true

    - name: Import Jenkins key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
      become: true

    - name: update dnf repo
      command: sudo dnf upgrade



    - name: Install Jenkins
      dnf:
        name: jenkins
        state: latest
      become: true

    # - name: Install Jenkins package
    #   yum:
    #     name: jenkins
    #     state: present
    #   become: true

    # - name: Copy files
    #   become: true
    #   copy:
    #     src: ./jenkinsdata.tar.gz
    #     dest: /var/lib/jenkins/


    - name: Unarchive the file
      become: true
      ansible.builtin.unarchive:
        src: jenkinsdata.tar.gz  # Replace with the actual path to your archive
        dest: /var/lib/jenkins        # Replace with the desired destination directory
        group: jenkins
        owner: jenkins

    - name: Move files
      become: true
      ansible.builtin.copy:
        src: /var/lib/jenkins/jenkinsdata/
        dest: /var/lib/jenkins
        group: jenkins
        owner: jenkins
        remote_src: yes

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: true
      become: true

    # - name: Read initialAdminPassword file
    #   shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    #   register: jenkins_admin_password
    #   become: true

    # - name: Display Jenkins initial admin password
    #   debug:
    #     var: jenkins_admin_password.stdout


    # - name: Stop Jenkins 
    #   service:
    #     name: jenkins 
    #     state: stopped 
    #   become: true 
    #   tags: [never, stop-jenkins]

